// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: genomedb/v1/genome.proto

package genomedbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GeneIds []string `protobuf:"bytes,2,rep,name=gene_ids,json=geneIds,proto3" json:"gene_ids,omitempty"`
}

func (x *Genome) Reset() {
	*x = Genome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genomedb_v1_genome_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genome) ProtoMessage() {}

func (x *Genome) ProtoReflect() protoreflect.Message {
	mi := &file_genomedb_v1_genome_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genome.ProtoReflect.Descriptor instead.
func (*Genome) Descriptor() ([]byte, []int) {
	return file_genomedb_v1_genome_proto_rawDescGZIP(), []int{0}
}

func (x *Genome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genome) GetGeneIds() []string {
	if x != nil {
		return x.GeneIds
	}
	return nil
}

type GenomeServiceGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenomeName string `protobuf:"bytes,1,opt,name=genome_name,json=genomeName,proto3" json:"genome_name,omitempty"`
}

func (x *GenomeServiceGetRequest) Reset() {
	*x = GenomeServiceGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genomedb_v1_genome_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenomeServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenomeServiceGetRequest) ProtoMessage() {}

func (x *GenomeServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genomedb_v1_genome_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenomeServiceGetRequest.ProtoReflect.Descriptor instead.
func (*GenomeServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_genomedb_v1_genome_proto_rawDescGZIP(), []int{1}
}

func (x *GenomeServiceGetRequest) GetGenomeName() string {
	if x != nil {
		return x.GenomeName
	}
	return ""
}

type GenomeServiceGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genome *Genome `protobuf:"bytes,1,opt,name=genome,proto3" json:"genome,omitempty"`
}

func (x *GenomeServiceGetResponse) Reset() {
	*x = GenomeServiceGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genomedb_v1_genome_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenomeServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenomeServiceGetResponse) ProtoMessage() {}

func (x *GenomeServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genomedb_v1_genome_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenomeServiceGetResponse.ProtoReflect.Descriptor instead.
func (*GenomeServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_genomedb_v1_genome_proto_rawDescGZIP(), []int{2}
}

func (x *GenomeServiceGetResponse) GetGenome() *Genome {
	if x != nil {
		return x.Genome
	}
	return nil
}

type GenomeServiceListGenomeNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *GenomeServiceListGenomeNamesResponse) Reset() {
	*x = GenomeServiceListGenomeNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genomedb_v1_genome_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenomeServiceListGenomeNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenomeServiceListGenomeNamesResponse) ProtoMessage() {}

func (x *GenomeServiceListGenomeNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genomedb_v1_genome_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenomeServiceListGenomeNamesResponse.ProtoReflect.Descriptor instead.
func (*GenomeServiceListGenomeNamesResponse) Descriptor() ([]byte, []int) {
	return file_genomedb_v1_genome_proto_rawDescGZIP(), []int{3}
}

func (x *GenomeServiceListGenomeNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_genomedb_v1_genome_proto protoreflect.FileDescriptor

var file_genomedb_v1_genome_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x65, 0x6e, 0x6f,
	0x6d, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x75, 0x73, 0x49, 0x64, 0x73, 0x22,
	0x3a, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x18, 0x47,
	0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x6f, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65,
	0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x24, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x32, 0xc5, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x24, 0x2e, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x31, 0x2e, 0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x65,
	0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f,
	0x67, 0x65, 0x6e, 0x6f, 0x6d, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x65, 0x6e, 0x6f,
	0x6d, 0x65, 0x64, 0x62, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genomedb_v1_genome_proto_rawDescOnce sync.Once
	file_genomedb_v1_genome_proto_rawDescData = file_genomedb_v1_genome_proto_rawDesc
)

func file_genomedb_v1_genome_proto_rawDescGZIP() []byte {
	file_genomedb_v1_genome_proto_rawDescOnce.Do(func() {
		file_genomedb_v1_genome_proto_rawDescData = protoimpl.X.CompressGZIP(file_genomedb_v1_genome_proto_rawDescData)
	})
	return file_genomedb_v1_genome_proto_rawDescData
}

var file_genomedb_v1_genome_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_genomedb_v1_genome_proto_goTypes = []interface{}{
	(*Genome)(nil),                               // 0: genomedb.v1.Genome
	(*GenomeServiceGetRequest)(nil),              // 1: genomedb.v1.GenomeServiceGetRequest
	(*GenomeServiceGetResponse)(nil),             // 2: genomedb.v1.GenomeServiceGetResponse
	(*GenomeServiceListGenomeNamesResponse)(nil), // 3: genomedb.v1.GenomeServiceListGenomeNamesResponse
	(*emptypb.Empty)(nil),                        // 4: google.protobuf.Empty
}
var file_genomedb_v1_genome_proto_depIdxs = []int32{
	0, // 0: genomedb.v1.GenomeServiceGetResponse.genome:type_name -> genomedb.v1.Genome
	1, // 1: genomedb.v1.GenomeService.Get:input_type -> genomedb.v1.GenomeServiceGetRequest
	4, // 2: genomedb.v1.GenomeService.ListGenomeNames:input_type -> google.protobuf.Empty
	2, // 3: genomedb.v1.GenomeService.Get:output_type -> genomedb.v1.GenomeServiceGetResponse
	3, // 4: genomedb.v1.GenomeService.ListGenomeNames:output_type -> genomedb.v1.GenomeServiceListGenomeNamesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_genomedb_v1_genome_proto_init() }
func file_genomedb_v1_genome_proto_init() {
	if File_genomedb_v1_genome_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genomedb_v1_genome_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genomedb_v1_genome_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenomeServiceGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genomedb_v1_genome_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenomeServiceGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_genomedb_v1_genome_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenomeServiceListGenomeNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genomedb_v1_genome_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genomedb_v1_genome_proto_goTypes,
		DependencyIndexes: file_genomedb_v1_genome_proto_depIdxs,
		MessageInfos:      file_genomedb_v1_genome_proto_msgTypes,
	}.Build()
	File_genomedb_v1_genome_proto = out.File
	file_genomedb_v1_genome_proto_rawDesc = nil
	file_genomedb_v1_genome_proto_goTypes = nil
	file_genomedb_v1_genome_proto_depIdxs = nil
}
