// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"genomedb/ent/keggreaction"
	"genomedb/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KeggReactionDelete is the builder for deleting a KeggReaction entity.
type KeggReactionDelete struct {
	config
	hooks    []Hook
	mutation *KeggReactionMutation
}

// Where appends a list predicates to the KeggReactionDelete builder.
func (krd *KeggReactionDelete) Where(ps ...predicate.KeggReaction) *KeggReactionDelete {
	krd.mutation.Where(ps...)
	return krd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (krd *KeggReactionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(krd.hooks) == 0 {
		affected, err = krd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KeggReactionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			krd.mutation = mutation
			affected, err = krd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(krd.hooks) - 1; i >= 0; i-- {
			if krd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = krd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, krd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (krd *KeggReactionDelete) ExecX(ctx context.Context) int {
	n, err := krd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (krd *KeggReactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: keggreaction.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: keggreaction.FieldID,
			},
		},
	}
	if ps := krd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, krd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// KeggReactionDeleteOne is the builder for deleting a single KeggReaction entity.
type KeggReactionDeleteOne struct {
	krd *KeggReactionDelete
}

// Exec executes the deletion query.
func (krdo *KeggReactionDeleteOne) Exec(ctx context.Context) error {
	n, err := krdo.krd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{keggreaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (krdo *KeggReactionDeleteOne) ExecX(ctx context.Context) {
	krdo.krd.ExecX(ctx)
}
