// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"genomedb/ent/genome"
	"genomedb/ent/predicate"
	"genomedb/ent/scaffold"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScaffoldUpdate is the builder for updating Scaffold entities.
type ScaffoldUpdate struct {
	config
	hooks    []Hook
	mutation *ScaffoldMutation
}

// Where appends a list predicates to the ScaffoldUpdate builder.
func (su *ScaffoldUpdate) Where(ps ...predicate.Scaffold) *ScaffoldUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetSeqname sets the "seqname" field.
func (su *ScaffoldUpdate) SetSeqname(s string) *ScaffoldUpdate {
	su.mutation.SetSeqname(s)
	return su
}

// SetSeq sets the "seq" field.
func (su *ScaffoldUpdate) SetSeq(s string) *ScaffoldUpdate {
	su.mutation.SetSeq(s)
	return su
}

// SetGenomeID sets the "genome" edge to the Genome entity by ID.
func (su *ScaffoldUpdate) SetGenomeID(id string) *ScaffoldUpdate {
	su.mutation.SetGenomeID(id)
	return su
}

// SetNillableGenomeID sets the "genome" edge to the Genome entity by ID if the given value is not nil.
func (su *ScaffoldUpdate) SetNillableGenomeID(id *string) *ScaffoldUpdate {
	if id != nil {
		su = su.SetGenomeID(*id)
	}
	return su
}

// SetGenome sets the "genome" edge to the Genome entity.
func (su *ScaffoldUpdate) SetGenome(g *Genome) *ScaffoldUpdate {
	return su.SetGenomeID(g.ID)
}

// Mutation returns the ScaffoldMutation object of the builder.
func (su *ScaffoldUpdate) Mutation() *ScaffoldMutation {
	return su.mutation
}

// ClearGenome clears the "genome" edge to the Genome entity.
func (su *ScaffoldUpdate) ClearGenome() *ScaffoldUpdate {
	su.mutation.ClearGenome()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ScaffoldUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScaffoldMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *ScaffoldUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ScaffoldUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ScaffoldUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ScaffoldUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scaffold.Table,
			Columns: scaffold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scaffold.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Seqname(); ok {
		_spec.SetField(scaffold.FieldSeqname, field.TypeString, value)
	}
	if value, ok := su.mutation.Seq(); ok {
		_spec.SetField(scaffold.FieldSeq, field.TypeString, value)
	}
	if su.mutation.GenomeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scaffold.GenomeTable,
			Columns: []string{scaffold.GenomeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: genome.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.GenomeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scaffold.GenomeTable,
			Columns: []string{scaffold.GenomeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: genome.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scaffold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ScaffoldUpdateOne is the builder for updating a single Scaffold entity.
type ScaffoldUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScaffoldMutation
}

// SetSeqname sets the "seqname" field.
func (suo *ScaffoldUpdateOne) SetSeqname(s string) *ScaffoldUpdateOne {
	suo.mutation.SetSeqname(s)
	return suo
}

// SetSeq sets the "seq" field.
func (suo *ScaffoldUpdateOne) SetSeq(s string) *ScaffoldUpdateOne {
	suo.mutation.SetSeq(s)
	return suo
}

// SetGenomeID sets the "genome" edge to the Genome entity by ID.
func (suo *ScaffoldUpdateOne) SetGenomeID(id string) *ScaffoldUpdateOne {
	suo.mutation.SetGenomeID(id)
	return suo
}

// SetNillableGenomeID sets the "genome" edge to the Genome entity by ID if the given value is not nil.
func (suo *ScaffoldUpdateOne) SetNillableGenomeID(id *string) *ScaffoldUpdateOne {
	if id != nil {
		suo = suo.SetGenomeID(*id)
	}
	return suo
}

// SetGenome sets the "genome" edge to the Genome entity.
func (suo *ScaffoldUpdateOne) SetGenome(g *Genome) *ScaffoldUpdateOne {
	return suo.SetGenomeID(g.ID)
}

// Mutation returns the ScaffoldMutation object of the builder.
func (suo *ScaffoldUpdateOne) Mutation() *ScaffoldMutation {
	return suo.mutation
}

// ClearGenome clears the "genome" edge to the Genome entity.
func (suo *ScaffoldUpdateOne) ClearGenome() *ScaffoldUpdateOne {
	suo.mutation.ClearGenome()
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ScaffoldUpdateOne) Select(field string, fields ...string) *ScaffoldUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Scaffold entity.
func (suo *ScaffoldUpdateOne) Save(ctx context.Context) (*Scaffold, error) {
	var (
		err  error
		node *Scaffold
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ScaffoldMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Scaffold)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ScaffoldMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ScaffoldUpdateOne) SaveX(ctx context.Context) *Scaffold {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ScaffoldUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ScaffoldUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ScaffoldUpdateOne) sqlSave(ctx context.Context) (_node *Scaffold, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   scaffold.Table,
			Columns: scaffold.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: scaffold.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Scaffold.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scaffold.FieldID)
		for _, f := range fields {
			if !scaffold.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scaffold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Seqname(); ok {
		_spec.SetField(scaffold.FieldSeqname, field.TypeString, value)
	}
	if value, ok := suo.mutation.Seq(); ok {
		_spec.SetField(scaffold.FieldSeq, field.TypeString, value)
	}
	if suo.mutation.GenomeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scaffold.GenomeTable,
			Columns: []string{scaffold.GenomeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: genome.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.GenomeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scaffold.GenomeTable,
			Columns: []string{scaffold.GenomeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: genome.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Scaffold{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scaffold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
