// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"genomedb/ent/gene"
	"genomedb/ent/genome"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Gene is the model entity for the Gene schema.
type Gene struct {
	config
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GeneQuery when eager-loading is set.
	Edges        GeneEdges `json:"edges"`
	genome_genes *string
}

// GeneEdges holds the relations/edges for other nodes in the graph.
type GeneEdges struct {
	// Transcripts holds the value of the transcripts edge.
	Transcripts []*Transcript `json:"transcripts,omitempty"`
	// Genome holds the value of the genome edge.
	Genome *Genome `json:"genome,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TranscriptsOrErr returns the Transcripts value or an error if the edge
// was not loaded in eager-loading.
func (e GeneEdges) TranscriptsOrErr() ([]*Transcript, error) {
	if e.loadedTypes[0] {
		return e.Transcripts, nil
	}
	return nil, &NotLoadedError{edge: "transcripts"}
}

// GenomeOrErr returns the Genome value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GeneEdges) GenomeOrErr() (*Genome, error) {
	if e.loadedTypes[1] {
		if e.Genome == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: genome.Label}
		}
		return e.Genome, nil
	}
	return nil, &NotLoadedError{edge: "genome"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Gene) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gene.FieldID:
			values[i] = new(sql.NullString)
		case gene.ForeignKeys[0]: // genome_genes
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Gene", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Gene fields.
func (ge *Gene) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gene.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ge.ID = value.String
			}
		case gene.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field genome_genes", values[i])
			} else if value.Valid {
				ge.genome_genes = new(string)
				*ge.genome_genes = value.String
			}
		}
	}
	return nil
}

// QueryTranscripts queries the "transcripts" edge of the Gene entity.
func (ge *Gene) QueryTranscripts() *TranscriptQuery {
	return (&GeneClient{config: ge.config}).QueryTranscripts(ge)
}

// QueryGenome queries the "genome" edge of the Gene entity.
func (ge *Gene) QueryGenome() *GenomeQuery {
	return (&GeneClient{config: ge.config}).QueryGenome(ge)
}

// Update returns a builder for updating this Gene.
// Note that you need to call Gene.Unwrap() before calling this method if this Gene
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *Gene) Update() *GeneUpdateOne {
	return (&GeneClient{config: ge.config}).UpdateOne(ge)
}

// Unwrap unwraps the Gene entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ge *Gene) Unwrap() *Gene {
	_tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: Gene is not a transactional entity")
	}
	ge.config.driver = _tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *Gene) String() string {
	var builder strings.Builder
	builder.WriteString("Gene(")
	builder.WriteString(fmt.Sprintf("id=%v", ge.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Genes is a parsable slice of Gene.
type Genes []*Gene

func (ge Genes) config(cfg config) {
	for _i := range ge {
		ge[_i].config = cfg
	}
}
