// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"genomedb/ent/goterm"
	"genomedb/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoTermDelete is the builder for deleting a GoTerm entity.
type GoTermDelete struct {
	config
	hooks    []Hook
	mutation *GoTermMutation
}

// Where appends a list predicates to the GoTermDelete builder.
func (gtd *GoTermDelete) Where(ps ...predicate.GoTerm) *GoTermDelete {
	gtd.mutation.Where(ps...)
	return gtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gtd *GoTermDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gtd.hooks) == 0 {
		affected, err = gtd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoTermMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gtd.mutation = mutation
			affected, err = gtd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gtd.hooks) - 1; i >= 0; i-- {
			if gtd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gtd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gtd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gtd *GoTermDelete) ExecX(ctx context.Context) int {
	n, err := gtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gtd *GoTermDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: goterm.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: goterm.FieldID,
			},
		},
	}
	if ps := gtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GoTermDeleteOne is the builder for deleting a single GoTerm entity.
type GoTermDeleteOne struct {
	gtd *GoTermDelete
}

// Exec executes the deletion query.
func (gtdo *GoTermDeleteOne) Exec(ctx context.Context) error {
	n, err := gtdo.gtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{goterm.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gtdo *GoTermDeleteOne) ExecX(ctx context.Context) {
	gtdo.gtd.ExecX(ctx)
}
