// Code generated by ent, DO NOT EDIT.

package keggontology

const (
	// Label holds the string label denoting the keggontology type in the database.
	Label = "kegg_ontology"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// Table holds the table name of the keggontology in the database.
	Table = "kegg_ontologies"
)

// Columns holds all SQL columns for keggontology fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSymbol,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
